
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.item;

import com.google.gson.JsonElement;


public final class ConfigItem {
    private final java.util.HashMap<Integer, TbItem> _dataMap;
    private final java.util.ArrayList<TbItem> _dataList;
    
    public ConfigItem(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, TbItem>();
        _dataList = new java.util.ArrayList<TbItem>();
        
        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            TbItem _v;
            _v = TbItem.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, TbItem> getDataMap() { return _dataMap; }
    public java.util.ArrayList<TbItem> getDataList() { return _dataList; }

    public TbItem get(int key) { return _dataMap.get(key); }

}
