
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.item;

import com.google.gson.JsonObject;
import org.sunrise.game.game.config.luban.AbstractBean;


public final class TbItem extends AbstractBean {
    public TbItem(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        desc = _buf.get("desc").getAsString();
        price = _buf.get("price").getAsInt();
        upgradeToItemId = _buf.get("upgrade_to_item_id").getAsInt();
        batchUseable = _buf.get("batch_useable").getAsBoolean();
    }

    public static TbItem deserialize(JsonObject _buf) {
            return new TbItem(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 价格
     */
    public final int price;
    /**
     * 引用当前表
     */
    public final int upgradeToItemId;
    /**
     * 能否批量使用
     */
    public final boolean batchUseable;

    public static final int __ID__ = -1825431044;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "price:" + price + ","
        + "upgradeToItemId:" + upgradeToItemId + ","
        + "batchUseable:" + batchUseable + ","
        + "}";
    }
}

