
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.param;

import com.google.gson.JsonElement;
import org.sunrise.game.game.config.luban.SerializationException;


public final class ConfigParam {
    private final TbParam _data;

    public final TbParam data() { return _data; }

    public ConfigParam(JsonElement _buf) {
        int n = _buf.getAsJsonArray().size();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = TbParam.deserialize(_buf.getAsJsonArray().get(0).getAsJsonObject().getAsJsonObject());
    }


    /**
     * 背包容量
     */
     public int getItemBoxCapacity() { return _data.ItemBoxCapacity; }
    /**
     * 物品最大堆叠数量
     */
     public int getItemMaxStack() { return _data.ItemMaxStack; }
    /**
     * 新角色初始化任务列表
     */
     public java.util.ArrayList<Integer> getTaskInitIds() { return _data.TaskInitIds; }
    /**
     * 新角色初始化地图id
     */
     public int getMapInitId() { return _data.MapInitId; }

}
