
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.param;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbParam extends AbstractBean {
    public TbParam(JsonObject _buf) { 
        ItemBoxCapacity = _buf.get("ItemBoxCapacity").getAsInt();
        ItemMaxStack = _buf.get("ItemMaxStack").getAsInt();
        { com.google.gson.JsonArray _json0_ = _buf.get("TaskInitIds").getAsJsonArray(); TaskInitIds = new java.util.ArrayList<Integer>(_json0_.size()); for(JsonElement _e0 : _json0_) { int _v0;  _v0 = _e0.getAsInt();  TaskInitIds.add(_v0); }   }
        MapInitId = _buf.get("MapInitId").getAsInt();
        GMCmdStatus = _buf.get("GMCmdStatus").getAsInt();
        DefaultHeadIcon = _buf.get("DefaultHeadIcon").getAsInt();
    }

    public static TbParam deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.param.TbParam(_buf);
    }

    /**
     * 背包容量
     */
    public final int ItemBoxCapacity;
    /**
     * 物品最大堆叠数量
     */
    public final int ItemMaxStack;
    /**
     * 新角色初始化任务列表
     */
    public final java.util.ArrayList<Integer> TaskInitIds;
    /**
     * 新角色初始化地图id
     */
    public final int MapInitId;
    /**
     * gm指令开启状态
     */
    public final int GMCmdStatus;
    /**
     * 新角色默认头像
     */
    public final int DefaultHeadIcon;

    public static final int __ID__ = -196947394;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "ItemBoxCapacity:" + ItemBoxCapacity + ","
        + "ItemMaxStack:" + ItemMaxStack + ","
        + "TaskInitIds:" + TaskInitIds + ","
        + "MapInitId:" + MapInitId + ","
        + "GMCmdStatus:" + GMCmdStatus + ","
        + "DefaultHeadIcon:" + DefaultHeadIcon + ","
        + "}";
    }
}

