
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.drop;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;


public final class ConfigDropGroup {
    private final java.util.HashMap<Integer, org.sunrise.game.game.config.drop.TbDropGroup> _dataMap;
    private final java.util.ArrayList<org.sunrise.game.game.config.drop.TbDropGroup> _dataList;
    
    public ConfigDropGroup(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, org.sunrise.game.game.config.drop.TbDropGroup>();
        _dataList = new java.util.ArrayList<org.sunrise.game.game.config.drop.TbDropGroup>();
        
        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            org.sunrise.game.game.config.drop.TbDropGroup _v;
            _v = org.sunrise.game.game.config.drop.TbDropGroup.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, org.sunrise.game.game.config.drop.TbDropGroup> getDataMap() { return _dataMap; }
    public java.util.ArrayList<org.sunrise.game.game.config.drop.TbDropGroup> getDataList() { return _dataList; }

    public org.sunrise.game.game.config.drop.TbDropGroup get(int key) { return _dataMap.get(key); }

}
