
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.drop;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbDropGroup extends AbstractBean {
    public TbDropGroup(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        type = _buf.get("type").getAsInt();
        { com.google.gson.JsonArray _json0_ = _buf.get("drop_ids").getAsJsonArray(); dropIds = new java.util.ArrayList<Integer>(_json0_.size()); for(JsonElement _e0 : _json0_) { int _v0;  _v0 = _e0.getAsInt();  dropIds.add(_v0); }   }
    }

    public static TbDropGroup deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.drop.TbDropGroup(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 抽取类型：1=抽一个，2=全随
     */
    public final int type;
    /**
     * 关联的 drop 表 id 列表
     */
    public final java.util.ArrayList<Integer> dropIds;

    public static final int __ID__ = -2117803677;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "dropIds:" + dropIds + ","
        + "}";
    }
}

