
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.drop;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbDrop extends AbstractBean {
    public TbDrop(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        itemId = _buf.get("item_id").getAsInt();
        countMin = _buf.get("count_min").getAsInt();
        countMax = _buf.get("count_max").getAsInt();
        weight = _buf.get("weight").getAsInt();
    }

    public static TbDrop deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.drop.TbDrop(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 物品配置ID
     */
    public final int itemId;
    /**
     * 最少掉落数量
     */
    public final int countMin;
    /**
     * 最大掉落数量  
     */
    public final int countMax;
    /**
     *  权重（1-10000），roll到此范围内掉落
     */
    public final int weight;

    public static final int __ID__ = -998944132;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "itemId:" + itemId + ","
        + "countMin:" + countMin + ","
        + "countMax:" + countMax + ","
        + "weight:" + weight + ","
        + "}";
    }
}

