jdbc.url=jdbc:mysql://127.0.0.1:3306/sunrise
jdbc.user=root
jdbc.password=123456
jdbc.pool.auto-reconnect=true
jdbc.pool.maximum-size=5
jdbc.pool.minimum-idle=3
jdbc.pool.connection-timeout=30000
jdbc.pool.idle-timeout=600000
jdbc.pool.max-lifetime=1800000
