
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.Enum;

public final class ActivityStatus {
    /**
     * 未开启
     */
    public static final int NOT_OPEN = 0;
    /**
     * 进行中
     */
    public static final int DOING = 1;
    /**
     * 已结束
     */
    public static final int END = 2;
}

