
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.Enum;

public final class ActivityType {
    /**
     * 签到活动
     */
    public static final int CheckIn = 1;
    /**
     * 充值活动
     */
    public static final int Recharge = 2;
    /**
     * 登录活动
     */
    public static final int Login = 3;
}

