
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.Enum;

public final class AttributeType {
    /**
     * 生命值
     */
    public static final int HP = 1;
    /**
     * 法力值
     */
    public static final int MP = 2;
    /**
     * 攻击力
     */
    public static final int ATTACK = 3;
    /**
     * 防御力
     */
    public static final int DEFENSE = 4;
    /**
     * 速度
     */
    public static final int SPEED = 5;
    /**
     * 暴击率（0~1之间的小数）
     */
    public static final int CRIT_RATE = 6;
    /**
     * 暴击伤害倍率（1.5表示暴击150%伤害）
     */
    public static final int CRIT_DAMAGE = 7;
    /**
     * 闪避率
     */
    public static final int DODGE = 8;
    /**
     * 命中率
     */
    public static final int HIT = 9;
    /**
     * 最大生命值
     */
    public static final int MAX_HP = 10;
    /**
     * 最大法力值
     */
    public static final int MAX_MP = 11;
    /**
     * 生命回复（每秒）
     */
    public static final int HP_RECOVER = 12;
    /**
     * 法力回复（每秒）
     */
    public static final int MP_RECOVER = 13;
    /**
     * 攻击力百分比加成（0.1表示+10%）
     */
    public static final int ATTACK_PERCENT = 14;
    /**
     * 防御力百分比加成
     */
    public static final int DEFENSE_PERCENT = 15;
    /**
     * 生命值百分比加成
     */
    public static final int HP_PERCENT = 16;
    /**
     * 法力值百分比加成
     */
    public static final int MP_PERCENT = 17;
    /**
     * 速度百分比加成
     */
    public static final int SPEED_PERCENT = 18;
}

