
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.Enum;

public final class TaskStatus {
    /**
     * 进行中
     */
    public static final int DOING = 0;
    /**
     * 已完成
     */
    public static final int FINISH = 1;
    /**
     * 已提交
     */
    public static final int SUBMIT = 2;
}

