
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.Enum;

public final class TaskType {
    public static final int LEVEL_UP = 1;
    public static final int EXP_ADD = 2;
    public static final int ITEM_USE = 3;
    public static final int ITEM_GET = 4;
    public static final int KILL_MONSTER = 5;
}

