# connect http
http.address=${HTTP_ADDRESS:127.0.0.1}
#http.address=www.goldminer.cloud
http.port=8090

# Options: TRACE, DEBUG, INFO, WARN, ERROR
log.level=INFO

# Options: websocket, tcp, kcp
client.socket=tcp
