jdbc.url=${JDBC_URL:jdbc:mysql://127.0.0.1:3306/sunrise}
jdbc.user=${JDBC_USER:root}
jdbc.password=${JDBC_PASSWORD:123456}
jdbc.maximumPoolSize=5
jdbc.minimumIdle=3
jdbc.connectionTimeout=30000
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000

# connect master
master.id=1
master.address=${MASTER_ADDRESS:127.0.0.1}
master.port=8000
# external rpcNode report address
report.address=${REPORT_ADDRESS:127.0.0.1}
external.address=${EXTERNAL_ADDRESS:127.0.0.1}

external.listen.tcp=true
external.listen.ws=true
external.listen.kcp=true
# The maximum number of messages received by a single client per minute
external.msgcountpermin = 1000

rpc.node.type=external
rpc.node.serverId=100

# Options: TRACE, DEBUG, INFO, WARN, ERROR
log.level=DEBUG
