jdbc.url=jdbc:mysql://127.0.0.1:3306/sunrise
jdbc.user=root
jdbc.password=123456
jdbc.maximumPoolSize=5
jdbc.minimumIdle=3
jdbc.connectionTimeout=30000
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000

# connect master
master.id=1
master.address=127.0.0.1
master.port=8000
# game rpcNode report address
report.address=127.0.0.1

# Options: TRACE, DEBUG, INFO, WARN, ERROR
log.level=DEBUG

# config path
config.path=E:/java/sunrise-game-frame/tables/json