jdbc.url=jdbc:mysql://127.0.0.1:3306/sunrise
jdbc.user=root
jdbc.password=123456
jdbc.maximumPoolSize=5
jdbc.minimumIdle=3
jdbc.connectionTimeout=30000
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000

# connect master
# id = 0 not connect master
master.id=0
master.address=127.0.0.1
master.port=8000
report.address=127.0.0.1
# external report address
external.address=127.0.0.1

external.listen.tcp=true
external.listen.ws=true
external.listen.kcp=true
# The maximum number of messages received by a single client per minute
external.msgcountpermin = 1000

rpc.node.type=game
rpc.node.serverId=100

# Options: TRACE, DEBUG, INFO, WARN, ERROR
log.level=INFO

# config path
config.path=E:/sunrise-game-frame/tables/json

admin.user=admin
admin.password=sunrise
admin.port=8010
admin.jwt.expiration=864000000

# http bind
http.port=8090

# login queue: max logins allowed per second (direct + dequeue)
login.queue.maxPerSecond=100