
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;

public final class Tables
{
    public interface IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }

    private final org.sunrise.game.game.config.item.ConfigItem _configitem;
    public static volatile org.sunrise.game.game.config.item.ConfigItem ConfigItem;
    private org.sunrise.game.game.config.item.ConfigItem getConfigItem() { return _configitem; }
    private final org.sunrise.game.game.config.param.ConfigParam _configparam;
    public static volatile org.sunrise.game.game.config.param.ConfigParam ConfigParam;
    private org.sunrise.game.game.config.param.ConfigParam getConfigParam() { return _configparam; }
    private final org.sunrise.game.game.config.task.ConfigTask _configtask;
    public static volatile org.sunrise.game.game.config.task.ConfigTask ConfigTask;
    private org.sunrise.game.game.config.task.ConfigTask getConfigTask() { return _configtask; }
    private final org.sunrise.game.game.config.map.ConfigMap _configmap;
    public static volatile org.sunrise.game.game.config.map.ConfigMap ConfigMap;
    private org.sunrise.game.game.config.map.ConfigMap getConfigMap() { return _configmap; }
    private final org.sunrise.game.game.config.activity.ConfigActivity _configactivity;
    public static volatile org.sunrise.game.game.config.activity.ConfigActivity ConfigActivity;
    private org.sunrise.game.game.config.activity.ConfigActivity getConfigActivity() { return _configactivity; }
    private final org.sunrise.game.game.config.monster.ConfigMonster _configmonster;
    public static volatile org.sunrise.game.game.config.monster.ConfigMonster ConfigMonster;
    private org.sunrise.game.game.config.monster.ConfigMonster getConfigMonster() { return _configmonster; }
    private final org.sunrise.game.game.config.drop.ConfigDrop _configdrop;
    public static volatile org.sunrise.game.game.config.drop.ConfigDrop ConfigDrop;
    private org.sunrise.game.game.config.drop.ConfigDrop getConfigDrop() { return _configdrop; }
    private final org.sunrise.game.game.config.drop.ConfigDropGroup _configdropgroup;
    public static volatile org.sunrise.game.game.config.drop.ConfigDropGroup ConfigDropGroup;
    private org.sunrise.game.game.config.drop.ConfigDropGroup getConfigDropGroup() { return _configdropgroup; }

    public Tables(IJsonLoader loader) throws java.io.IOException {
        _configitem = new org.sunrise.game.game.config.item.ConfigItem(loader.load("item_configitem"));
        _configparam = new org.sunrise.game.game.config.param.ConfigParam(loader.load("param_configparam"));
        _configtask = new org.sunrise.game.game.config.task.ConfigTask(loader.load("task_configtask"));
        _configmap = new org.sunrise.game.game.config.map.ConfigMap(loader.load("map_configmap"));
        _configactivity = new org.sunrise.game.game.config.activity.ConfigActivity(loader.load("activity_configactivity"));
        _configmonster = new org.sunrise.game.game.config.monster.ConfigMonster(loader.load("monster_configmonster"));
        _configdrop = new org.sunrise.game.game.config.drop.ConfigDrop(loader.load("drop_configdrop"));
        _configdropgroup = new org.sunrise.game.game.config.drop.ConfigDropGroup(loader.load("drop_configdropgroup"));
    }

    public static void load(Tables tables) {
        if (tables == null) return;
        ConfigItem = tables.getConfigItem(); 
        ConfigParam = tables.getConfigParam(); 
        ConfigTask = tables.getConfigTask(); 
        ConfigMap = tables.getConfigMap(); 
        ConfigActivity = tables.getConfigActivity(); 
        ConfigMonster = tables.getConfigMonster(); 
        ConfigDrop = tables.getConfigDrop(); 
        ConfigDropGroup = tables.getConfigDropGroup(); 
    }
}

