
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.monster;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbMonster extends AbstractBean {
    public TbMonster(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        level = _buf.get("level").getAsInt();
        mapId = _buf.get("map_id").getAsInt();
        spawnX = _buf.get("spawn_x").getAsInt();
        spawnY = _buf.get("spawn_y").getAsFloat();
        spawnZ = _buf.get("spawn_z").getAsFloat();
        respawnTime = _buf.get("respawn_time").getAsInt();
        hp = _buf.get("hp").getAsDouble();
        mp = _buf.get("mp").getAsDouble();
        attack = _buf.get("attack").getAsDouble();
        defense = _buf.get("defense").getAsDouble();
        speed = _buf.get("speed").getAsDouble();
        hpRecover = _buf.get("hp_recover").getAsDouble();
        mpRecover = _buf.get("mp_recover").getAsDouble();
        attackPercent = _buf.get("attack_percent").getAsDouble();
        defensePercent = _buf.get("defense_percent").getAsDouble();
        hpPercent = _buf.get("hp_percent").getAsDouble();
        mpPercent = _buf.get("mp_percent").getAsDouble();
        speedPercent = _buf.get("speed_percent").getAsDouble();
    }

    public static TbMonster deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.monster.TbMonster(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    public final int level;
    public final int mapId;
    public final int spawnX;
    public final float spawnY;
    public final float spawnZ;
    public final int respawnTime;
    /**
     * 生命值
     */
    public final double hp;
    /**
     * 法力值
     */
    public final double mp;
    /**
     * 攻击力
     */
    public final double attack;
    /**
     * 防御力
     */
    public final double defense;
    /**
     * 速度
     */
    public final double speed;
    /**
     * 生命回复
     */
    public final double hpRecover;
    /**
     * 法力回复
     */
    public final double mpRecover;
    /**
     * 攻击力百分比加成
     */
    public final double attackPercent;
    /**
     * 防御力百分比加成
     */
    public final double defensePercent;
    /**
     * 生命值百分比加成
     */
    public final double hpPercent;
    /**
     * 法力值百分比加成
     */
    public final double mpPercent;
    /**
     * 速度百分比加成
     */
    public final double speedPercent;

    public static final int __ID__ = -1601139624;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "level:" + level + ","
        + "mapId:" + mapId + ","
        + "spawnX:" + spawnX + ","
        + "spawnY:" + spawnY + ","
        + "spawnZ:" + spawnZ + ","
        + "respawnTime:" + respawnTime + ","
        + "hp:" + hp + ","
        + "mp:" + mp + ","
        + "attack:" + attack + ","
        + "defense:" + defense + ","
        + "speed:" + speed + ","
        + "hpRecover:" + hpRecover + ","
        + "mpRecover:" + mpRecover + ","
        + "attackPercent:" + attackPercent + ","
        + "defensePercent:" + defensePercent + ","
        + "hpPercent:" + hpPercent + ","
        + "mpPercent:" + mpPercent + ","
        + "speedPercent:" + speedPercent + ","
        + "}";
    }
}

