
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.monsterRefresh;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbMonsterRefresh extends AbstractBean {
    public TbMonsterRefresh(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        monsterId = _buf.get("monster_id").getAsInt();
        mapId = _buf.get("map_id").getAsInt();
        spawnX = _buf.get("spawn_x").getAsInt();
        spawnY = _buf.get("spawn_y").getAsFloat();
        spawnZ = _buf.get("spawn_z").getAsFloat();
        respawnTime = _buf.get("respawn_time").getAsInt();
    }

    public static TbMonsterRefresh deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.monsterRefresh.TbMonsterRefresh(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 怪物id
     */
    public final int monsterId;
    public final int mapId;
    public final int spawnX;
    public final float spawnY;
    public final float spawnZ;
    public final int respawnTime;

    public static final int __ID__ = 281051260;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "monsterId:" + monsterId + ","
        + "mapId:" + mapId + ","
        + "spawnX:" + spawnX + ","
        + "spawnY:" + spawnY + ","
        + "spawnZ:" + spawnZ + ","
        + "respawnTime:" + respawnTime + ","
        + "}";
    }
}

