
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.map;

import com.google.gson.JsonElement;


public final class ConfigMap {
    private final java.util.HashMap<Integer, TbMap> _dataMap;
    private final java.util.ArrayList<TbMap> _dataList;
    
    public ConfigMap(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, TbMap>();
        _dataList = new java.util.ArrayList<TbMap>();
        
        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            TbMap _v;
            _v = TbMap.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, TbMap> getDataMap() { return _dataMap; }
    public java.util.ArrayList<TbMap> getDataList() { return _dataList; }

    public TbMap get(int key) { return _dataMap.get(key); }

}
