
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.map;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbMap extends AbstractBean {
    public TbMap(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        desc = _buf.get("desc").getAsString();
        type = _buf.get("type").getAsInt();
        CliId = _buf.get("Cli_id").getAsInt();
        enterX = _buf.get("enter_x").getAsFloat();
        enterY = _buf.get("enter_y").getAsFloat();
        enterZ = _buf.get("enter_z").getAsFloat();
    }

    public static TbMap deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.map.TbMap(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 类型
     */
    public final int type;
    public final int CliId;
    /**
     * 进入坐标
     */
    public final float enterX;
    public final float enterY;
    public final float enterZ;

    public static final int __ID__ = -176452388;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "type:" + type + ","
        + "CliId:" + CliId + ","
        + "enterX:" + enterX + ","
        + "enterY:" + enterY + ","
        + "enterZ:" + enterZ + ","
        + "}";
    }
}

