jdbc.url=jdbc:mysql://mysql:3306/sunrise
jdbc.user=root
jdbc.password=123456
jdbc.maximumPoolSize=5
jdbc.minimumIdle=3
jdbc.connectionTimeout=30000
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000

master.id=1
master.address=center
master.port=8000
report.address=gmback

admin.user=admin
admin.password=sunrise
admin.port=8010
admin.jwt.expiration=864000000

log.level=INFO
