
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.activity;

import com.google.gson.JsonElement;


public final class ConfigActivity {
    private final java.util.HashMap<Integer, TbActivity> _dataMap;
    private final java.util.ArrayList<TbActivity> _dataList;
    
    public ConfigActivity(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, TbActivity>();
        _dataList = new java.util.ArrayList<TbActivity>();
        
        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            TbActivity _v;
            _v = TbActivity.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, TbActivity> getDataMap() { return _dataMap; }
    public java.util.ArrayList<TbActivity> getDataList() { return _dataList; }

    public TbActivity get(int key) { return _dataMap.get(key); }

}
