
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.activity;

import com.google.gson.JsonObject;
import org.sunrise.game.game.config.luban.AbstractBean;


public final class TbActivity extends AbstractBean {
    public TbActivity(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        type = _buf.get("type").getAsInt();
        name = _buf.get("name").getAsString();
        desc = _buf.get("desc").getAsString();
        levelLimit = _buf.get("level_limit").getAsInt();
        naturalTime = _buf.get("natural_time").getAsInt();
        beginTime = _buf.get("begin_time").getAsString();
        endTime = _buf.get("end_time").getAsString();
        humanCreate = _buf.get("human_create").getAsInt();
        durationTime = _buf.get("duration_time").getAsInt();
    }

    public static TbActivity deserialize(JsonObject _buf) {
            return new TbActivity(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 活动类型
     */
    public final int type;
    /**
     * 名字
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 等级限制
     */
    public final int levelLimit;
    /**
     * 是否为自然时间
     */
    public final int naturalTime;
    /**
     * 活动开始时间
     */
    public final String beginTime;
    /**
     * 活动结束时间
     */
    public final String endTime;
    /**
     * 是否用角色创建时间
     */
    public final int humanCreate;
    /**
     * 活动持续天数（不走自然时间时使用）
     */
    public final int durationTime;

    public static final int __ID__ = 364965884;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "levelLimit:" + levelLimit + ","
        + "naturalTime:" + naturalTime + ","
        + "beginTime:" + beginTime + ","
        + "endTime:" + endTime + ","
        + "humanCreate:" + humanCreate + ","
        + "durationTime:" + durationTime + ","
        + "}";
    }
}

