
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.task;

import com.google.gson.JsonElement;


public final class ConfigTask {
    private final java.util.HashMap<Integer, TbTask> _dataMap;
    private final java.util.ArrayList<TbTask> _dataList;
    
    public ConfigTask(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, TbTask>();
        _dataList = new java.util.ArrayList<TbTask>();
        
        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            TbTask _v;
            _v = TbTask.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.HashMap<Integer, TbTask> getDataMap() { return _dataMap; }
    public java.util.ArrayList<TbTask> getDataList() { return _dataList; }

    public TbTask get(int key) { return _dataMap.get(key); }

}
