
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package org.sunrise.game.game.config.task;

import org.sunrise.game.luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class TbTask extends AbstractBean {
    public TbTask(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        desc = _buf.get("desc").getAsString();
        type = _buf.get("type").getAsInt();
        nextId = _buf.get("next_id").getAsInt();
        { com.google.gson.JsonArray _json0_ = _buf.get("task_params").getAsJsonArray(); taskParams = new java.util.ArrayList<Integer>(_json0_.size()); for(JsonElement _e0 : _json0_) { int _v0;  _v0 = _e0.getAsInt();  taskParams.add(_v0); }   }
        goal = _buf.get("goal").getAsInt();
    }

    public static TbTask deserialize(JsonObject _buf) {
            return new org.sunrise.game.game.config.task.TbTask(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    /**
     * 描述
     */
    public final String desc;
    /**
     * 类型
     */
    public final int type;
    /**
     * 引用当前表，没有下一个任务的就是独立的，比如等级任务就是同时全部接取。杀怪任务，完成一个接下一个
     */
    public final int nextId;
    /**
     * 参数
     */
    public final java.util.ArrayList<Integer> taskParams;
    /**
     * 目标值
     */
    public final int goal;

    public static final int __ID__ = 596827580;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "type:" + type + ","
        + "nextId:" + nextId + ","
        + "taskParams:" + taskParams + ","
        + "goal:" + goal + ","
        + "}";
    }
}

